component: user
service_type: ClusterIP
port: 80
container_port: 8080
target_port: 8080
PARAMETERS_ENABLED: true
PARAMETERS: "user.prod.DOCUMENTDB,DOCUMENTDB user.prod.MONGO_URL,MONGO_URL user.prod.REDIS_HOST,REDIS_HOST"
schema_type: DOCDB
schema_enabled: true