name: User Application

on:
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: workstation
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Compile & Build
      run: npm install

    - name: Upload Node Modules artifact
      uses: actions/upload-artifact@v4
      with:
        name: node-modules
        path: node_modules

  test:
    needs: compile
    runs-on: workstation
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Run Test Cases
      # run: npm test
      run: echo Test Cases Passed

  sonarqube-scan:
    needs: test
    runs-on: workstation
    steps:    
    - uses: actions/checkout@v4
    
    - name: Download Node Modules artifact
      uses: actions/download-artifact@v4
      with:
        name: node-modules
        path: node_modules
      
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      with:
        args: >
          -Dsonar.projectKey="user"
          -Dsonar.exclusions=**/Dockerfile
          
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      with:
        pollingTimeoutSec: 600
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        
  code-security:
    needs: sonarqube-scan
    runs-on: workstation
    steps:
    - uses: actions/checkout@v4

    - name: Code Security
      run: echo Code Security

  push_to_ecr:
    needs: code-security
    runs-on: workstation
    name: Build Docker Images and Push to AWS ECR
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set build number tag
      id: build-number
      run: |
        echo "tag=${{ github.run_number }}" >> $GITHUB_OUTPUT

    - name: Download Node Modules artifact
      uses: actions/download-artifact@v4
      with:
        name: node-modules
        path: node_modules

    - name: Build and push to Amazon ECR
      if: github.ref_name == 'main'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          058264090525.dkr.ecr.us-east-1.amazonaws.com/user:${{ steps.build-number.outputs.tag }}
        no-cache: true

    - name: Build and push to Amazon ECR
      if: github.ref_name == 'stage'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          058264090525.dkr.ecr.us-east-1.amazonaws.com/user-stage:${{ steps.build-number.outputs.tag }}
        no-cache: true

  deploy_to_eks:
    needs: push_to_ecr
    runs-on: workstation
    name: Deploy Image to EKS

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Update EKS Kube-Config
      run: |
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          aws eks update-kubeconfig --name prod-eks-cluster --region us-east-1
        elif [[ "${{ github.ref_name }}" == "stage" ]]; then
          aws eks update-kubeconfig --name stage-eks-cluster --region us-east-1
        else
          echo No other cluster is configured
        fi

    - name: Checkout APP code
      uses: actions/checkout@v4
      with:
        repository: Revanthsatyam/user
        path: APP
          
    - name: Checkout CHART code
      uses: actions/checkout@v4
      with:
        repository: Revanthsatyam/roboshop-helm-d76
        path: CHART

    - name: Set build number tag
      id: build-number
      run: |
        echo "tag=${{ github.run_number }}" >> $GITHUB_OUTPUT

    - name: Deploy with Helm
      run: |
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          helm upgrade --install user ./CHART -f APP/helm/prod.yaml \
          --set image_tag=${{ steps.build-number.outputs.tag }}
        elif [[ "${{ github.ref_name }}" == "stage" ]]; then
          helm upgrade --install user ./CHART -f APP/helm/stage.yaml \
          --set image_tag=${{ steps.build-number.outputs.tag }}
        else
          echo Nothing to deploy
        fi
        
